# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目名')),
                ('repo', models.CharField(max_length=32, verbose_name='仓库地址')),
                ('env', models.CharField(choices=[('prod', '正式'), ('test', '测试')], default='test', max_length=16, verbose_name='环境')),
            ],
        ),
    ]
