# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-18 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='path',
            field=models.CharField(default='/data/temp/', max_length=32, verbose_name='线上项目地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='servers',
            field=models.ManyToManyField(to='app01.Server', verbose_name='关联服务器'),
        ),
    ]
